# @package _global_
tags: null
project_name: "T Maze"
seed: 1
steps: 5000000
log_interval: 10000
eval_interval: null
save_interval: null
task: 
  task: tmazev2
  corridor_len: 180
  num_distractors: 6
  max_steps: null
  max_episode_steps: 1000

trainer:
  agent: a2c
  rollout_len: 256
  num_envs: 8
  seq_model:
    name: agalite
    n_layers: 4
    d_model: 128
    d_head: 64
    d_ffc: 128
    n_heads: 4
    eta: 4
    r: 2
    reset_hidden_on_terminate: true
  d_actor: 128
  d_critic: 128
  gamma: 0.99
  lamb: 0.95
  entropy_coef: 0.001
  value_coef: 0.5
  max_grad_norm: 0.5
  optimizer:
    learning_rate: 0.0001
  arg_max: false

use_wandb: true
